<Project Sdk="Aspire.AppHost.Sdk/13.1.1">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>507a670a-b7e0-4705-97b7-94ed708c9a64</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Livekit.Example.Api/Livekit.Example.Api.csproj" />
    <ProjectReference Include="../../LivekitAspire/LivekitAspire.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.1.1" />
  </ItemGroup>

</Project>
